name: Trigger Jenkins Job

# Someone must go to GitHub → Actions → Select workflow → Run workflow.
on:
  workflow_dispatch:

jobs:
  trigger:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        # Downloads and executes the GitHub Action named jenkins-action.
        uses: appleboy/jenkins-action@master
        # Inputs passed to that Action.
        with:
          # Jenkins server URL
          url: ${{ secrets.URL }}
          # Jenkins username from ui
          user: ${{ secrets.USER }}
          # Jenkins API token from ui configure and then API Token generate
          token: ${{ secrets.TOKEN }}
          # Jenkins job name is the name of item that you are already created in Jenkins dashboard
          job: ${{ secrets.JOBS }}
